version: '3.8'

services:
  api:
    image: dangroleau/root-to-rise-api
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - pgadmin
    environment:
      - SPRING_PROFILES_ACTIVE=dev-docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgresql:
        container_name: postgres
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: root_to_rise
        ports:
          - "5432:5432"
  pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - "5050:80"
