name: Push docker container to Heroku

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: mvn clean install
        run: mvn clean install -DskipTests

      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
      
      - name: Build Container
        env: 
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web -a root-to-rise-api

      - name: Release Container
        env: 
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a root-to-rise-api
